Checks:
  - Name: "License Exists"
    AllowedToFail: true
  - Name: ".gitignore exists"
    AllowedToFail: true
  - Name: "README exists"
    AllowedToFail: true
  - Name: "GitHub Workflow exists"
    AllowedToFail: true
  - Name: "Secrets check"
    AllowedToFail: true
  - Name: "Tests exists"
    AllowedToFail: true

PathToSaveGitRepos: "~/git_repos"