@startuml SystemContextDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "Developer", "A person who wants to know if the repository is following best practices")

Container(repositoryLinterSystem, "Repository Linter", "A program that checks a repository for best practices.")

Rel(personAlias, repositoryLinterSystem, "Starts linter", "using the CLI with a URL or a local path as arguments")

System_Ext(external_services_secret, "External Services", "Services that the repository uses, like databases or APIs.")
Rel(repositoryLinterSystem, external_services_secret, "Accesses", "to test the found and identified secrets found by TruffleHog")

System_Ext(git_hoster, "Git Repository Hoster", "A service that hosts git repositories, like GitHub or GitLab.")
Rel(repositoryLinterSystem, git_hoster, "Clones", "the repository")
@enduml